### ISSUE TITLE
PiHole compatability

### ISSUE THREAD

**Issue by p1r473** [DRSDavidSoft/additional-hosts#1]
Hi David,
Possible to make this more PiHole friendly and remove domains starting with *. as these wildcards do not work with the PiHole.

**Comment by p1r473** [comment]
@DRSDavidSoft * does not work in hostsfiles/Pihole so please remove these 

pagead*.googlesyndication.com
imageads*.googleadservices.com
*.googleadservices.com
*.googletagservices.com
*.doubleclick.net
*.doublecklick.net
*.2mdn.net
*.admob.com
*.admob.xiaomi.com
*.adnxs.com
*.applift.com
*.applovin.com
*.applvn.com
*.adswizz.com
*.batmobi.net
*.batmobil.net
*.comscore.com
*.mycomscore.net
*.mycomscore.com
settings-crashlytics-*.us-east-1.elb.amazonaws.com
settings-crashlytics-*.*.elb.amazonaws.com
*.fastclick.net
*.ads.linkedin.com
*.pubmatic.com
*.mojiva.com
*.ads.mojiva.com
*.mocean.mobi
*.voicefive.com
*.thewhizmarketing.com
*.lp.mydas.mobi
*.ads.mp.mydas.mobi
*.w.inmobi.com
*.inmobi.com
ads-*.spotify.com
*.audio2.spotify.com
pixel*.spotify.com
*.video-ak.cdn.spotify.com
*.er.spo.spotify.com
*.spotx.tv
*.msecn.net
*.atdmt.com
*.amazon-adsystem.com
*.media-match.com
*.omaze.com
*.tune.com
*.moatads.com
*.smaato.net
*.jumptap.com
*.appads.com
jupiter*.appads.com
neptune*.appads.com
saturn*.appads.com
req*.appads.com
*.adinfuse.com
*.smartadserver.com
*.advertising.com

**Comment by Casperr2k19** [comment]
57 domains invalid!

**Comment by DRSDavidSoft** [comment]
@p1r473 @Casperr2k19 Thank you for reporting this issue, and bringing this to me.  I'll validate the lines and remove them from the list so it won't contain the invalid domains.

@Casperr2k19 Can you please also post the 57 domains here? Thanks

**Comment by p1r473** [comment]
> @p1r473 @Casperr2k19 Thank you for reporting this issue, and bringing this to me. I'll validate the lines and remove them from the list so it won't contain the invalid domains.
> 
> @Casperr2k19 Can you please also post the 57 domains here? Thanks

I posted them in the original post
If you meant to have wildcards in there, they dont break anything, but note they arent valid if used as a hosts file (they will be ignored... doesnt break anything though)

**Comment by DRSDavidSoft** [comment]
Sorry that this issue has been open for so long. I moved the wildcard domains into another file, so Pi-hole would be compatible!
