### ISSUE TITLE
PersianBlocker

### ISSUE THREAD

**Issue by MasterKia** [DRSDavidSoft/additional-hosts#10]
درود. دیدم لیست های کنونی پارسی زبان خیلی پراکنده و گستردگی دارن، تصمیم گرفتم همشون رو توی یک لیست به نام [PersianBlocker](https://github.com/MasterKia/PersianBlocker) تجمیع بکنم.
پیشنهاد کردم که این لیست رو جایگزین لیست پارسی uBlock Origin و AdGuard کنن. فعلاً Maintainer های uBO نظر موافق دارن و باید صبر کرد تا لیست افزوده بشه.
از محتوای لیست شما هم بهره خواهم برد و [اینجا](https://github.com/MasterKia/PersianBlocker#%DA%AF%D8%B1%D8%A7%D9%85%DB%8C%D8%AF%D8%A7%D8%B4%D8%AA) ازش یاد کردم.
سپاس بابت این لیست عالی.

https://github.com/MasterKia/PersianBlocker/commit/bedebb1494383a5ad7559f7e801f5e737b8ae7d7

**Comment by MasterKia** [comment]
@DRSDavidSoft

**Comment by DRSDavidSoft** [comment]
بسیار خوشحال خواهم شد در صورت official شدن نسبت به contribution به طور مستقیم به لیست زیبای شما اقدام کنم، ضمناً خوشحال خواهم شد به‌صورت دوره‌ای کماکان لیست بنده را هم داخل PersianBlocker بگنجانید تا دیگران نیز بهره‌مند شوند.

> دیدم لیست های کنونی پارسی زبان خیلی پراکنده و گستردگی دارن، تصمیم گرفتم همشون رو توی یک لیست به نام [PersianBlocker](https://github.com/MasterKia/PersianBlocker) تجمیع بکنم.

بسیار به این نکته که پراکندگی وجود داره نیز موافق هستم؛ البته اهداف developer های این لیست ها هم کمی با هم متفاوت هست (به عنوان مثال اینجا: https://github.com/SlashArash/adblockfa/issues/4#issuecomment-351743263 یکی از تفاوت‌های اهداف ذکر شده).

اگر که ادقام لیست‌ها با موفقیت انجام بشه، بطوری که maintain کردنشون به‌صورت دوره‌ای توسط contributor ها درست انجام بشه که قطعاً موفقیت بزرگی خواهد بود.

این مورد من رو به یاد xkcd زیر میندازه:

<img src="https://imgs.xkcd.com/comics/standards_2x.png" />

**Comment by MasterKia** [comment]
> در صورت official شدن

News flash:

لیست [افیشیال](https://github.com/gorhill/uBlock/commit/33b839fdd03f74689df3ee2b5c25a06435b350e0) شد :-)
البته این لیست به افزونه AdGuard هم پیشنهاد شده اما اونا محتاط تر هستن و یکم دست نگه میدارن ببینن نگهداری و توسعه لیست چقدر هست.


> لیست بنده را هم داخل PersianBlocker بگنجانید تا دیگران نیز بهره‌مند شوند.

حتماً. هنوز لیست شما رو به طور کامل نگنجوندم، اما در دست اقدام هست. البته قبلش باید لینک های ازکارافتاده رو به کمک ابزار PyFunceble شناسایی و حذف بکنم.




> اهداف developer های این لیست ها هم کمی با هم متفاوت هست

بله، ظاهراً رویکرد جناب @SlashArash برای لیست Adblock Farsi این بوده:
1- فیلتر کردن سایت‌های تبلغات کلیکی
2- فیلتر کردن کلمات و نشانه‌های عمومی
3- سایت‌های خاصی که توسط دو مورد قبل فیلتر نشدند رو به صورت مشخص فیلتر کنن
و فرموده بودن که در لیست Adblock-Iran بیشتر مورد سوم رعایت شده.

1: من در لیست PersianBlocker مورد اول رو در قالب [Persian Ads/Trackers](https://github.com/MasterKia/PersianBlocker/blob/main/PersianBlocker.txt#L31) لحاظ کردم که _خیلی_ هم مفید و موثر واقع بود، چون بیشتر سایت ها تبلیغاتشون رو ازین دست موارد میگیرن و از خودشون تبلیغی ندارن.

2: مورد دوم رو زیاد موافق نیستم چون فیلتر های عمومی  (Generic) میتونه باعث خرابی (Breakage) در برخی سایت های انگلیسی زبان (و حتی پارسی زبان) بشه اما در حین توسعه و گسترش دادن لیست PersianBlocker، واژه ها و عبارت هایی که هی تکرار میشن رو در قالب [Experimental Generic Filters](https://github.com/MasterKia/PersianBlocker/blob/main/PersianBlocker.txt#L12) لحاظ کردم که البته همشون فعلاً به صورت کامنت هستن.
ضمناً فیلتر های عمومی (Generic) روی بهینگی و سرعت افزونه مسدودساز اثر منفی میذارن.

3: بخش زیادی از لیست PersianBlocker رو همین مورد سوم تشکیل داده که بیشترین تمرکز من هم روی همین مورد بود.



> این مورد من رو به یاد xkcd زیر میندازه:

xDDDDD

مشکلی که منم داشتم دقیقاً همین بود، تا چند ماه پیش هر بار که افزونه مسدودساز رو نصب میکردم مجبور بودم سه لیست (Adblock-Iran، Adblock Farsi و uBOPa) رو روشون فعّال بکنم. با این حال بازم تبلیغای برخی سایتا از دستشون در میرفت.
تازه Issue هم که براشون باز میکردی، کسی نبود پاسخت رو بده (البته به جز سازنده لیست uBOPa که همکاری _خیلی_ خوبی داشتن) و باید خودت به صورت دستی توی My filters فیلتر اضافه میکردی.
یه جاهایی هم که به Maintainer های uAssets (uBlock Origin) متوسل میشدم و اونا فیلتر های پارسی زبان رو توی لیست هاشون میگنجوندن.
اما خوشبختانه ازون مشکلات گذر کردیم و خلاص شدیم.
