### ISSUE TITLE
JWPlayer

### ISSUE THREAD

**Issue by p1r473** [DRSDavidSoft/additional-hosts#2]
Hello,
Currently, you are blocking JWPlayer that breaks embedded videos in smartphone-ads-tracking.txt 
Example: embedded video on https://www.investopedia.com/terms/s/stop-limitorder.asp
Domains that need unblocking:
content.jwplatform.com
These domains are not spying or ad-related or malicious. They are just required for the playing of the JWPlayer content.

**Comment by DRSDavidSoft** [comment]
@p1r473 Sorry for the late response.

Can you please (re)-verify that JWPlayer is still not functional on the domain you specified?  I wasn't able to see any videos on the page.

Additionally, a screenshot would be appreciated.  Thanks for using my list!

**Comment by p1r473** [comment]
If you dont see the video than you are indeed blocking it ;)
I have tested extensively and that domain is blocking the playing of the video
I have whitelisted it on my end

![image](https://user-images.githubusercontent.com/9235633/96355266-b0692700-10ad-11eb-9c30-4eddead011fd.png)

**Comment by badmojr** [comment]
I can confirm this to be the case, @DRSDavidSoft .
Please fix.

**Comment by DRSDavidSoft** [comment]
@p1r473 @badmojr I removed `content.jwplatform.com`, sorry for the long delay. Thank you for using my list, hopefully there are no other false positives at this point!
