### ISSUE TITLE
Block domains

### ISSUE THREAD

**Issue by nRafinia** [DRSDavidSoft/additional-hosts#6]
Hi
Please add this domain to the blacklist.

redlini.ga
cdn.kaprila.com
cdn.hostdl.com
beta.kaprila.com

**Comment by DRSDavidSoft** [comment]
@nRafinia Sorry for the delay!

The `redlini.ga` and `*.kaprila.com` domains are already added, may I ask where `cdn.hostdl.com` is used? I believe HostDL are a reputable hosting provider for download websites, I guess you may be referring to the animated banners present in those websites.

I will add it to my list once I'm sure it won't interfere with other stuff.

**Comment by DRSDavidSoft** [comment]
@nRafinia I've added `redlini.ga` and the `redlin` **`i`** `.ga` domains into my list. I won't be adding `cdn.hostdl.com` at the moment, I believe uBlock Origin's cosmetic element hiders are better suited for this kind of ads removal.

Thank you for your report, and thank you for using my list!
