### ISSUE TITLE
Varzesh3 not working

### ISSUE THREAD

**Issue by mohalisad** [DRSDavidSoft/additional-hosts#7]
Hey
Because blocking of static.farakav.com varzesh3 is not showing correct

Can you expect that domain from the list?

**Comment by badmojr** [comment]
+1

**Comment by DRSDavidSoft** [comment]
@mohalisad I'm sorry for the late response, https://github.com/DRSDavidSoft/additional-hosts/commit/4ee9eb7d9810459a95dc464f9310558e32828ac9 removes this domain.
