### ISSUE TITLE
Phishing/typosquatt domain

### ISSUE THREAD

**Issue by iam-py-test** [DRSDavidSoft/additional-hosts#8]
### What domain are you submitting
`gogle.net`
### Why are you submitting this domain?
This domain is a known phishing and typosquatt domain.

**Comment by DRSDavidSoft** [comment]
@iam-py-test Thanks for the report!

I use and submit typosquatting domains to the `my-privacy-dns` list.  

A submit request into that repository exist here:
https://mypdns.org/my-privacy-dns/matrix/-/issues/1883

If you see any other typosquatt domains, feel free to report either here or in the `my-privacy-dns` repo.  In either of cases, the request will be merged. ❤️
